"""empty message

Revision ID: d9a66dc15793
Revises:
Create Date: 2020-01-06 21:35:42.555652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a66dc15793'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('state', sa.Column('dtnom', sa.DateTime(), nullable=True))
    op.add_column('state', sa.Column('dtstatic', sa.DateTime(), nullable=True))
    op.add_column('state', sa.Column('dtvote', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('state', 'dtvote')
    op.drop_column('state', 'dtstatic')
    op.drop_column('state', 'dtnom')
    # ### end Alembic commands ###
