"""empty message

Revision ID: e290ae408ae4
Revises: 85dc267ce8a1
Create Date: 2021-04-28 12:09:21.260182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e290ae408ae4'
down_revision = '85dc267ce8a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column('sessTokenTime',
            existing_type=sa.FLOAT(),
            type_=sa.Integer(),
            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column('sessTokenTime',
            existing_type=sa.Integer(),
            type_=sa.FLOAT(),
            existing_nullable=False)
    # ### end Alembic commands ###
